spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2306eze
    url: jdbc:postgresql://localhost:5432/postgres/souvenirs

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 80